<a href="https://colab.research.google.com/github/FarrelFach/Machine-Learning/blob/main/uts_7_3_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

path="/content/drive/MyDrive/Machine_Learning/UTS_datasets.csv"
df=pd.read_csv(path)
df.head()

,Unnamed: 0,id,name,artists,duration_ms,popularity,explicit,available_markets,add_date,playlist_id,album_id,album_name,album_artists,album_disc_number,album_track_number,album_total_tracks,album_type,album_release_date,album_release_date_precision,album_available_markets
0,0,5ueyLj6e6oVaTY0KQ6yLaA,All Shook Up,Elvis Presley,117080,61,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-06-09T22:02:00Z,37i9dQZF1DWSV3Tk4GO2fq,0C3t1htEDTFKcg7F2rNbek,Elvis' Golden Records,Elvis Presley,1,3,14,compilation,1958-03-21,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
1,1,3aEJMh1cXKEjgh52claxQp,I've Got You Under My Skin - Remastered 1998,Frank Sinatra,223760,68,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-06-09T22:02:00Z,37i9dQZF1DWSV3Tk4GO2fq,4kca7vXd1Wo5GE2DMafvMc,Songs For Swingin' Lovers! (Remastered),Frank Sinatra,1,9,15,album,1956-03,month,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
2,2,2vSxjnyrWrtxyfzO47EX6q,Smoke Gets In Your Eyes,The Platters,160933,64,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-06-09T22:02:00Z,37i9dQZF1DWSV3Tk4GO2fq,3hf24dCfmmDihusVyBLliZ,Remember When?,The Platters,1,2,12,album,1959-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
3,3,5yQ9iMZXGcr5rlO4hoLsP4,"What'd I Say, Pt. 1 & 2",Ray Charles,307053,61,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-06-09T22:02:00Z,37i9dQZF1DWSV3Tk4GO2fq,4tfWxufmH725XmTcQFAuXn,What'd I Say,Ray Charles,1,1,10,album,1959,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
4,4,3HuJDcOWx0gE9Yng2uWY7K,Dream A Little Dream Of Me,Louis Armstrong,196840,65,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-06-09T22:02:00Z,37i9dQZF1DWSV3Tk4GO2fq,6mmv0gwumlFGWDGJXF4yEv,What A Wonderful World,Louis Armstrong,1,4,11,album,1968-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."

In [3]:
from sklearn.model_selection import train_test_split
# proses partisi
x = df.drop(["explicit", "available_markets"],axis='columns')
y = df.drop(["album_name", "album_artists"],axis='columns')
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [4]:
x_train

,Unnamed: 0,id,name,artists,duration_ms,popularity,add_date,playlist_id,album_id,album_name,album_artists,album_disc_number,album_track_number,album_total_tracks,album_type,album_release_date,album_release_date_precision,album_available_markets
666,666,3tyTt5pEWblt96j1HsXiV5,Freedom! '90 - Remastered,George Michael,390861,64,2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,0ZeOyoJHPD6czbTPAT9Qaj,Listen Without Prejudice / MTV Unplugged (Deluxe),George Michael,1,2,37,album,2017-10-20,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
852,852,0DMRKqrpd0QO4RWiEdMib0,You Know I'm No Good,Amy Winehouse,257186,72,2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,0E4xv5gPjykrwBgBZzI8XG,Back To Black (Deluxe Edition),Amy Winehouse,1,2,19,album,2006,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
543,543,3gxEZXUjrNbl3TlSrTGbR5,Modern Love - 2018 Remaster,David Bowie,288339,68,2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,4NwG11AsDJluT732lSjMrV,Let's Dance (2018 Remaster),David Bowie,1,1,8,album,1983-04-14,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
185,185,6Ndauo9gCxNjTfklsFYS7b,You're All I Need To Get By,"Marvin Gaye, Tammi Terrell",173866,60,2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,1i1HqvvJk7zGpNDygYlXQd,You're All I Need,"Marvin Gaye, Tammi Terrell",1,3,12,album,1968-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
815,815,2aGw77pZqli064JiPuXYRi,I'm Like A Bird,Nelly Furtado,243160,70,2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,0emt7fmxNjW3lb37nTOXR0,"Whoa, Nelly! (Expanded Edition)",Nelly Furtado,1,5,22,album,2000,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,531,22wWxHGHRH8gZXNDXRgSqY,These Dreams,Heart,254476,64,2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,0zM8rTVzPoT7SD4ZMds430,Heart,Heart,1,4,10,album,1985-07-06,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
163,163,6iGU74CwXuT4XVepjc9Emf,God Only Knows - Mono / 1997 Remastered,The Beach Boys,173040,67,2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,6GphKx2QAPRoVGWE9D7ou8,Pet Sounds (Original Mono & Stereo Mix Versions),The Beach Boys,1,8,27,album,1966-06-16,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
521,521,0J8A1ZVyJcRZxFNvtp6jRh,One Day I'll Fly Away,Randy Crawford,302653,61,2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,1nC1gaO03Yk2lnbRZAN3KG,Now We May Begin,Randy Crawford,1,6,8,album,1980,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
261,261,2nvcTDmZkRWKNMAL29sLHo,The Night They Drove Old Dixie Down,The Band,211787,61,2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,4vXFiaDS8zuEl5bOUbW53x,The Band,The Band,1,3,12,album,1969-09-22,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
533,533,4gvea7UlDkAvsJBPZAd4oB,The Boys Of Summer,Don Henley,288733,76,2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,2x1s5aVQ01ylPs5nUdeA2i,Building The Perfect Beast,Don Henley,1,1,11,album,1984-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."

In [5]:
x_test

,Unnamed: 0,id,name,artists,duration_ms,popularity,add_date,playlist_id,album_id,album_name,album_artists,album_disc_number,album_track_number,album_total_tracks,album_type,album_release_date,album_release_date_precision,album_available_markets
645,645,12dU3vAh6AFoJkisorfoUl,Don't Look Back In Anger - Remastered,Oasis,289560,71,2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,6tOe4eAF8xNhEkl9WyvsE4,(What's The Story) Morning Glory? (Deluxe Rema...,Oasis,1,4,40,album,1995,year,"AT, AU, BE, CA, CH, CW, DE, DK, EE, ES, FI, FR..."
694,694,0IaMMHVbpJ0LrRAeigWOXr,Again,Janet Jackson,227133,58,2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,7qIuZgsMkRuh7rzi4qVcpg,Janet,Janet Jackson,1,19,28,album,1993-05-18,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
934,934,3AVrVz5rK8Hrqo9YGiVGN5,Apocalypse,Cigarettes After Sex,290146,82,2022-10-09T00:00:00Z,37i9dQZF1DX5Ejj0EkURtP,5bP82ZIls6rzhpf5Qu6AzC,Cigarettes After Sex,Cigarettes After Sex,1,4,10,album,2017-06-09,day,"AG, AO, AR, BB, BF, BI, BJ, BO, BR, BS, BW, BZ..."
1005,1005,3U4isOIWM3VvDubwSI3y7a,All of Me,John Legend,269560,84,2022-10-09T00:00:00Z,37i9dQZF1DX5Ejj0EkURtP,4OTAx9un4e6NfoHuVRiOrC,Love In The Future (Expanded Edition),John Legend,1,6,20,album,2013-08-30,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
215,215,6b6IMqP565TbtFFZg9iFf3,"I Can't Help Myself (Sugar Pie, Honey Bunch)",Four Tops,160280,72,2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,2jvkMPydCpLWwRothqJU1O,Four Tops Second Album,Four Tops,1,1,12,album,1965,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,711,42et6fnHCw1HIPSrdPprMl,Semi-Charmed Life,Third Eye Blind,268360,73,2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,2gToC0XAblE9h3UZD6aAaQ,Third Eye Blind,Third Eye Blind,1,3,14,album,1997-04-08,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
954,954,5O2P9iiztwhomNh8xkR9lJ,Night Changes,One Direction,226600,87,2022-10-09T00:00:00Z,37i9dQZF1DX5Ejj0EkURtP,4gCNyS7pidfK3rKWhB3JOY,FOUR (Deluxe),One Direction,1,7,16,album,2014-11-17,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
528,528,36lkJSDyMEZoWTqtRj8Q8q,You're the Inspiration - 2006 Remaster,Chicago,229240,72,2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,1ICKrl6sDjJD1YdR9VDfPR,Chicago 17 (Expanded & Remastered),Chicago,1,7,11,album,1984-05-14,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
182,182,3uCkIqD0VzQUijbs8WIizs,These Days,Nico,210653,63,2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,6O62Cqi0YqOytEbFmeLyjU,Chelsea Girl,Nico,1,2,10,album,1967-10-09,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
882,882,5QpaGzWp0hwB5faV8dkbAz,Wherever You Will Go,The Calling,208600,74,2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,2Ir1mtE8K61cCNY5WQyKGV,Camino Palmero,The Calling,1,3,11,album,2001,year,"AD, AE, AG, AL, AM, AO, AR, AZ, BA, BB, BD, BE..."

In [6]:
y_train

,Unnamed: 0,id,name,artists,duration_ms,popularity,explicit,available_markets,add_date,playlist_id,album_id,album_disc_number,album_track_number,album_total_tracks,album_type,album_release_date,album_release_date_precision,album_available_markets
666,666,3tyTt5pEWblt96j1HsXiV5,Freedom! '90 - Remastered,George Michael,390861,64,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,0ZeOyoJHPD6czbTPAT9Qaj,1,2,37,album,2017-10-20,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
852,852,0DMRKqrpd0QO4RWiEdMib0,You Know I'm No Good,Amy Winehouse,257186,72,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,0E4xv5gPjykrwBgBZzI8XG,1,2,19,album,2006,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
543,543,3gxEZXUjrNbl3TlSrTGbR5,Modern Love - 2018 Remaster,David Bowie,288339,68,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,4NwG11AsDJluT732lSjMrV,1,1,8,album,1983-04-14,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
185,185,6Ndauo9gCxNjTfklsFYS7b,You're All I Need To Get By,"Marvin Gaye, Tammi Terrell",173866,60,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,1i1HqvvJk7zGpNDygYlXQd,1,3,12,album,1968-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
815,815,2aGw77pZqli064JiPuXYRi,I'm Like A Bird,Nelly Furtado,243160,70,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,0emt7fmxNjW3lb37nTOXR0,1,5,22,album,2000,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,531,22wWxHGHRH8gZXNDXRgSqY,These Dreams,Heart,254476,64,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,0zM8rTVzPoT7SD4ZMds430,1,4,10,album,1985-07-06,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
163,163,6iGU74CwXuT4XVepjc9Emf,God Only Knows - Mono / 1997 Remastered,The Beach Boys,173040,67,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,6GphKx2QAPRoVGWE9D7ou8,1,8,27,album,1966-06-16,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
521,521,0J8A1ZVyJcRZxFNvtp6jRh,One Day I'll Fly Away,Randy Crawford,302653,61,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,1nC1gaO03Yk2lnbRZAN3KG,1,6,8,album,1980,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
261,261,2nvcTDmZkRWKNMAL29sLHo,The Night They Drove Old Dixie Down,The Band,211787,61,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,4vXFiaDS8zuEl5bOUbW53x,1,3,12,album,1969-09-22,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
533,533,4gvea7UlDkAvsJBPZAd4oB,The Boys Of Summer,Don Henley,288733,76,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,2x1s5aVQ01ylPs5nUdeA2i,1,1,11,album,1984-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."

In [7]:
y_train

,Unnamed: 0,id,name,artists,duration_ms,popularity,explicit,available_markets,add_date,playlist_id,album_id,album_disc_number,album_track_number,album_total_tracks,album_type,album_release_date,album_release_date_precision,album_available_markets
666,666,3tyTt5pEWblt96j1HsXiV5,Freedom! '90 - Remastered,George Michael,390861,64,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,0ZeOyoJHPD6czbTPAT9Qaj,1,2,37,album,2017-10-20,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
852,852,0DMRKqrpd0QO4RWiEdMib0,You Know I'm No Good,Amy Winehouse,257186,72,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,0E4xv5gPjykrwBgBZzI8XG,1,2,19,album,2006,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
543,543,3gxEZXUjrNbl3TlSrTGbR5,Modern Love - 2018 Remaster,David Bowie,288339,68,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,4NwG11AsDJluT732lSjMrV,1,1,8,album,1983-04-14,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
185,185,6Ndauo9gCxNjTfklsFYS7b,You're All I Need To Get By,"Marvin Gaye, Tammi Terrell",173866,60,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,1i1HqvvJk7zGpNDygYlXQd,1,3,12,album,1968-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
815,815,2aGw77pZqli064JiPuXYRi,I'm Like A Bird,Nelly Furtado,243160,70,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,0emt7fmxNjW3lb37nTOXR0,1,5,22,album,2000,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,531,22wWxHGHRH8gZXNDXRgSqY,These Dreams,Heart,254476,64,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,0zM8rTVzPoT7SD4ZMds430,1,4,10,album,1985-07-06,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
163,163,6iGU74CwXuT4XVepjc9Emf,God Only Knows - Mono / 1997 Remastered,The Beach Boys,173040,67,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,6GphKx2QAPRoVGWE9D7ou8,1,8,27,album,1966-06-16,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
521,521,0J8A1ZVyJcRZxFNvtp6jRh,One Day I'll Fly Away,Randy Crawford,302653,61,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,1nC1gaO03Yk2lnbRZAN3KG,1,6,8,album,1980,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
261,261,2nvcTDmZkRWKNMAL29sLHo,The Night They Drove Old Dixie Down,The Band,211787,61,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,4vXFiaDS8zuEl5bOUbW53x,1,3,12,album,1969-09-22,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
533,533,4gvea7UlDkAvsJBPZAd4oB,The Boys Of Summer,Don Henley,288733,76,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,2x1s5aVQ01ylPs5nUdeA2i,1,1,11,album,1984-01-01,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."

In [8]:
y_test

,Unnamed: 0,id,name,artists,duration_ms,popularity,explicit,available_markets,add_date,playlist_id,album_id,album_disc_number,album_track_number,album_total_tracks,album_type,album_release_date,album_release_date_precision,album_available_markets
645,645,12dU3vAh6AFoJkisorfoUl,Don't Look Back In Anger - Remastered,Oasis,289560,71,False,"AT, AU, BE, CA, CH, CW, DE, DK, EE, ES, FI, FR...",2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,6tOe4eAF8xNhEkl9WyvsE4,1,4,40,album,1995,year,"AT, AU, BE, CA, CH, CW, DE, DK, EE, ES, FI, FR..."
694,694,0IaMMHVbpJ0LrRAeigWOXr,Again,Janet Jackson,227133,58,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,7qIuZgsMkRuh7rzi4qVcpg,1,19,28,album,1993-05-18,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
934,934,3AVrVz5rK8Hrqo9YGiVGN5,Apocalypse,Cigarettes After Sex,290146,82,False,"AG, AO, AR, BB, BF, BI, BJ, BO, BR, BS, BW, BZ...",2022-10-09T00:00:00Z,37i9dQZF1DX5Ejj0EkURtP,5bP82ZIls6rzhpf5Qu6AzC,1,4,10,album,2017-06-09,day,"AG, AO, AR, BB, BF, BI, BJ, BO, BR, BS, BW, BZ..."
1005,1005,3U4isOIWM3VvDubwSI3y7a,All of Me,John Legend,269560,84,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-10-09T00:00:00Z,37i9dQZF1DX5Ejj0EkURtP,4OTAx9un4e6NfoHuVRiOrC,1,6,20,album,2013-08-30,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
215,215,6b6IMqP565TbtFFZg9iFf3,"I Can't Help Myself (Sugar Pie, Honey Bunch)",Four Tops,160280,72,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,2jvkMPydCpLWwRothqJU1O,1,1,12,album,1965,year,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,711,42et6fnHCw1HIPSrdPprMl,Semi-Charmed Life,Third Eye Blind,268360,73,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-11-11T00:00:00Z,37i9dQZF1DXbTxeAdrVG2l,2gToC0XAblE9h3UZD6aAaQ,1,3,14,album,1997-04-08,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
954,954,5O2P9iiztwhomNh8xkR9lJ,Night Changes,One Direction,226600,87,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-10-09T00:00:00Z,37i9dQZF1DX5Ejj0EkURtP,4gCNyS7pidfK3rKWhB3JOY,1,7,16,album,2014-11-17,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
528,528,36lkJSDyMEZoWTqtRj8Q8q,You're the Inspiration - 2006 Remaster,Chicago,229240,72,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-11T07:43:27Z,37i9dQZF1DX4UtSsGT1Sbe,1ICKrl6sDjJD1YdR9VDfPR,1,7,11,album,1984-05-14,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
182,182,3uCkIqD0VzQUijbs8WIizs,These Days,Nico,210653,63,False,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB...",2022-08-12T11:06:50Z,37i9dQZF1DXaKIA8E7WcJj,6O62Cqi0YqOytEbFmeLyjU,1,2,10,album,1967-10-09,day,"AD, AE, AG, AL, AM, AO, AR, AT, AU, AZ, BA, BB..."
882,882,5QpaGzWp0hwB5faV8dkbAz,Wherever You Will Go,The Calling,208600,74,False,"AD, AE, AG, AL, AM, AO, AR, AZ, BA, BB, BD, BE...",2022-10-26T11:28:36Z,37i9dQZF1DX4o1oenSJRJd,2Ir1mtE8K61cCNY5WQyKGV,1,3,11,album,2001,year,"AD, AE, AG, AL, AM, AO, AR, AZ, BA, BB, BD, BE..."